module.exports = [
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744569057,
    hostOnly: false,
    httpOnly: false,
    name: "_d2id",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "b77d1363-b231-467d-b2a7-15bebd36c309",
    id: 1,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1657738090,
    hostOnly: false,
    httpOnly: false,
    name: "_fbp",
    path: "/",
    sameSite: "lax",
    secure: false,
    session: false,
    storeId: "0",
    value: "fb.2.1649961082473.422630697",
    id: 2,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1657737081,
    hostOnly: false,
    httpOnly: false,
    name: "_gcl_au",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1.1.1416918106.1649961081",
    id: 3,
  },
  {
    domain: ".mercadopago.com.br",
    hostOnly: false,
    httpOnly: false,
    name: "_mp_ci",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: true,
    storeId: "0",
    value: "157788095.1649961034",
    id: 4,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1649962146,
    hostOnly: false,
    httpOnly: false,
    name: "_mp_dc",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1",
    id: 5,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1713034086,
    hostOnly: false,
    httpOnly: false,
    name: "_mp_ga",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.3.157788095.1649961034",
    id: 6,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1650048486,
    hostOnly: false,
    httpOnly: false,
    name: "_mp_ga_gid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "GA1.3.864262661.1649961079",
    id: 7,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1649962386.776778,
    hostOnly: false,
    httpOnly: false,
    name: "cookiesPreferencesLogged",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "%7B%22userId%22%3A42156231%2C%22categories%22%3A%7B%22advertising%22%3Atrue%7D%7D",
    id: 8,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1870713078.176486,
    hostOnly: false,
    httpOnly: true,
    name: "ftid",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "DZmPz5UbmttQwdvZTlCDrCssJ5qrsSmi-1649961033534",
    id: 9,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744634886.776824,
    hostOnly: false,
    httpOnly: true,
    name: "nsa_rotok",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "eyJhbGciOiJIUzI1NiIsImtpZCI6InYyIiwidHlwIjoiSldUIn0.eyJpZGVudGlmaWVyIjoiMWY5YWY1OGUtMDU3Yi00ZDA2LThlZjUtMmVjZmVjMzAwNzJmIiwicm90YXRpb25faWQiOiI0Yzk3MjdiYy0wM2VjLTQ0ZjctYjIwYi00NDhhY2Y4ODg1MGUiLCJwbGF0Zm9ybSI6Ik1QIiwicm90YXRpb25fZGF0ZSI6MTY0OTk2MjY4NiwiZXhwaXJlIjoxNjUwMDQ4NDg2LCJleHAiOjE2NTI1NTQwODYsImp0aSI6IjEyNDE0MmIxLTk4OGEtNDRmNS1iNmY4LTMwYzNiZWIyNjIxMyIsImlhdCI6MTY0OTk2MjA4Niwic3ViIjoiMWE0ODg4YTBiY2I2YWY5ZGFlZDc5ODhjZGYzMDYzNDdmMjc5OWUxNDg3NTdjODgzOWZlM2U2Y2VkYmViM2RiZiJ9.azVwIGaWcjMOUPusryXgwL0B-2hmbUD-GIo7a_QC2EQ",
    id: 10,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744569077.176431,
    hostOnly: false,
    httpOnly: false,
    name: "orgnickp",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "RAFAELCFLIMA",
    id: 11,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744569077.176416,
    hostOnly: false,
    httpOnly: false,
    name: "orguserid",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "hTZZ0H9tZH0",
    id: 12,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744569077.176467,
    hostOnly: false,
    httpOnly: false,
    name: "orguseridp",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "42156231",
    id: 13,
  },
  {
    domain: ".mercadopago.com.br",
    expirationDate: 1744569077.176369,
    hostOnly: false,
    httpOnly: true,
    name: "ssid",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "ghy-041414-6Qx6XMz4GdCERVpr1xWQBlxZGTiXvG-__-42156231-__-1744569077506--RRR_0-RRR_0",
    id: 14,
  },
  {
    domain: "www.mercadopago.com.br",
    hostOnly: true,
    httpOnly: true,
    name: "_csrf",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: true,
    storeId: "0",
    value: "d7PNAKW3nMaxEnRAsarpdJbv",
    id: 15,
  },
  {
    domain: "www.mercadopago.com.br",
    hostOnly: true,
    httpOnly: true,
    name: "NSESSIONID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value:
      "s%3A3jW6by-rEco_clO53VWKwKeF6hX8YpJx.JMY0ERXesDB4IewZiO51cCbNY57gzN6AAyQfgZf%2B7%2Bk",
    id: 16,
  },
];
